### ISSUE TITLE
Requirement and issues for ES upgrade

### ISSUE THREAD

**Issue by calvinyv** [QingCloudAppcenter/ELK#1]

**Comment by benjaminhuo** [comment]
# Requiement
## New version ES 5.x , current is 5.5
## Integration of the ELK stack, Install and config kibana and logstash in a user accessible client node

# Plugins
## Plugins for backup & restore
### S3 Repository Plugin
The S3 repository plugin adds support for using S3 as a repository for Snapshot/Restore.
https://www.elastic.co/guide/en/elasticsearch/plugins/5.5/repository-s3.html
### Hadoop HDFS Repository Plugin
https://www.elastic.co/guide/en/elasticsearch/plugins/5.5/repository-hdfs.html

## IK Analysis
https://github.com/medcl/elasticsearch-analysis-ik
### Integrate with sogou dictionary
### upload custom dictionary

## head
http://mobz.github.io/elasticsearch-head/
In ES 5.x , head is used in a different way.
Maybe can be installed on elastic search client node together with kibana and logstash

## searchguard
https://floragunn.com/searchguard/
https://github.com/floragunncom/search-guard

## elasticsearch-sql
https://github.com/NLPchina/elasticsearch-sql/wiki

## More plugins refer to link below and pick some useful plugins if necessary
https://www.elastic.co/guide/en/elasticsearch/plugins/5.5/index.html

**Comment by calvinyv** [comment]
more plugin candinates: kopf, bigdesk

**Comment by calvinyv** [comment]
E节点：
1.只有一个E角色，master和node都为true，随机（如何做到）选择一个节点设为false作为balancer节点？
2. 分master节点和balancer节点角色
L节点：
agent和central角色，
K节点：
一个节点

**Comment by jolestar** [comment]
1. jdk8
2. gc 日志收集以及 jvm core dump 分析机制
3. 慢查询日志汇总查看
4. es数据导入插件  mongodb（elasticsearch-river-mongodb），kafka
5. 考虑集成安全插件
4. 考虑集成 http://git.oschina.net/farmerx/ElasticHD 插件
